version: '3.8'

services:
  go:
    build: ./
    command: ./wait-for-postgres.sh db ./weather_telegram_bot
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./logs:/logs

  db:
    image: postgres:16.1-bullseye
    restart: always
    container_name: postgresWF
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=wfdb
    ports:
      - 5432:5432
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql