version: '3.8'

services:
  go:
    build: ./
    command: ./wait-for-postgres.sh db ./weather_telegram_bot
    depends_on:
      - db
      - cache
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./logs:/logs

  db:
    image: postgres:15.3-bullseye
    restart: always
    container_name: postgresWF
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=wfdb
    ports:
      - 5432:5432
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  cache:
    image: redis:7.2.3-bookworm 
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes