version: '3.8'

services:
  postgres:
    image: postgres:15.3-bullseye
    restart: always
    container_name: postgresWF
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: wfdb
    ports:
      - "5432:5432"
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql